//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fortuna.Adapter
{
    using System;
    using System.Collections.Generic;
    
    public partial class Faelles_Spiller
    {
        public long number { get; set; }
        public string name { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string Zip { get; set; }
        public string city { get; set; }
        public string country { get; set; }
        public string email { get; set; }
        public string telephone { get; set; }
        public string mobile { get; set; }
        public Nullable<bool> giro { get; set; }
        public string notes { get; set; }
        public Nullable<int> terminal { get; set; }
        public Nullable<bool> ll_customer { get; set; }
        public Nullable<bool> vl_customer { get; set; }
        public Nullable<System.DateTime> inactive { get; set; }
    }
}
