//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fortuna.Adapter
{
    using System;
    using System.Collections.Generic;
    
    public partial class Forhandler
    {
        public int ForhandlerNummer { get; set; }
        public string Navn { get; set; }
        public string Forretning { get; set; }
        public string ForhAdresse1 { get; set; }
        public string ForhAdresse2 { get; set; }
        public string ForhPostnummer { get; set; }
        public string ForhBy { get; set; }
        public string ForhLand { get; set; }
        public Nullable<long> ForhTelefon { get; set; }
        public Nullable<long> ForhMobil { get; set; }
        public string ForhMail { get; set; }
        public string ForhWeb { get; set; }
        public string PrivAdresse1 { get; set; }
        public string PrivAdresse2 { get; set; }
        public string PrivPostnummer { get; set; }
        public string PrivBy { get; set; }
        public string PrivLand { get; set; }
        public Nullable<long> PrivTelefon { get; set; }
        public Nullable<long> PrivMobil { get; set; }
        public string PrivMail { get; set; }
        public string PrivWeb { get; set; }
        public Nullable<long> CPR { get; set; }
        public Nullable<long> CVR { get; set; }
        public Nullable<bool> CPR_CVR { get; set; }
        public Nullable<bool> Moms { get; set; }
        public Nullable<System.DateTime> TiltraedelsesDato { get; set; }
        public Nullable<System.DateTime> AfgangsDato { get; set; }
        public Nullable<int> FlyttetFra { get; set; }
        public Nullable<System.DateTime> FlyttetFraDato { get; set; }
        public Nullable<int> FlyttetTil { get; set; }
        public Nullable<System.DateTime> FlyttetTilDato { get; set; }
        public Nullable<bool> Leverandoerservice { get; set; }
        public Nullable<long> LevKundenummer { get; set; }
        public Nullable<bool> AfregningMail { get; set; }
        public string Oplysninger { get; set; }
        public Nullable<decimal> SalgProvisionSats { get; set; }
        public Nullable<int> PosteringerId { get; set; }
        public Nullable<int> ForhandlerKontoRegNr { get; set; }
        public Nullable<long> ForhandlerKontoNr { get; set; }
        public Nullable<int> GevinstKontoRegNr { get; set; }
        public Nullable<long> GevinstKontoNr { get; set; }
        public Nullable<int> LeverandoerRegNr { get; set; }
        public Nullable<long> LeverandoerKontoNr { get; set; }
        public Nullable<long> GiroKontoNr { get; set; }
        public Nullable<int> BemaerkningsId { get; set; }
        public Nullable<int> Terminal { get; set; }
        public string Pin { get; set; }
        public string LoginId { get; set; }
        public Nullable<int> Terminal2 { get; set; }
        public string OprettetAf { get; set; }
        public string AendretAf { get; set; }
        public Nullable<System.DateTime> AendretDato { get; set; }
        public Nullable<decimal> BankGaranti { get; set; }
    }
}
