//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fortuna.Adapter
{
    using System;
    using System.Collections.Generic;
    
    public partial class PeriodeSkift
    {
        public int Periode { get; set; }
        public Nullable<System.DateTime> Dato { get; set; }
        public int Serie { get; set; }
        public Nullable<System.DateTime> StartDato { get; set; }
        public Nullable<System.DateTime> SlutDato { get; set; }
        public Nullable<System.DateTime> AfregningsDato { get; set; }
    }
}
