//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fortuna.Adapter
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tekster
    {
        public int idTekster { get; set; }
        public Nullable<int> Art { get; set; }
        public string Navn { get; set; }
        public string Tekst { get; set; }
        public Nullable<decimal> Vaerdi { get; set; }
    }
}
