//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fortuna.Adapter
{
    using System;
    using System.Collections.Generic;
    
    public partial class timingtry
    {
        public long nummer { get; set; }
        public string navn { get; set; }
        public int dato { get; set; }
    }
}
