//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fortuna.Adapter
{
    using System;
    using System.Collections.Generic;
    
    public partial class Traekning
    {
        public int Periode { get; set; }
        public Nullable<int> LodseddelNummer { get; set; }
        public Nullable<decimal> Beloeb { get; set; }
    }
}
