//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityAdapter
{
    using System;
    using System.Collections.Generic;
    
    public partial class Faelles_Forhandler
    {
        public long number { get; set; }
        public string name { get; set; }
        public string address { get; set; }
        public string Zip { get; set; }
        public string city { get; set; }
        public string country { get; set; }
        public string email { get; set; }
        public string telephone { get; set; }
        public string notes { get; set; }
        public Nullable<long> ll_number { get; set; }
        public Nullable<long> vl_number { get; set; }
        public Nullable<long> terminal { get; set; }
        public string pin { get; set; }
        public string login_id { get; set; }
        public Nullable<long> terminal2 { get; set; }
    }
}
