//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityAdapter
{
    using System;
    using System.Collections.Generic;
    
    public partial class Satser
    {
        public int idSatser { get; set; }
        public string SatsBeskrivelse { get; set; }
        public Nullable<decimal> Sats { get; set; }
        public Nullable<System.DateTime> Dato { get; set; }
        public string OprettetAf { get; set; }
        public string AendretAf { get; set; }
        public Nullable<System.DateTime> AendretDato { get; set; }
        public string Var { get; set; }
    }
}
