//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityAdapter
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spiller
    {
        public int idSpiller { get; set; }
        public string Fornavn { get; set; }
        public string Efternavn { get; set; }
        public string Adresse1 { get; set; }
        public string Adresse2 { get; set; }
        public string PostNummerId { get; set; }
        public string By { get; set; }
        public string Land { get; set; }
        public Nullable<long> Telefon { get; set; }
        public Nullable<long> Mobil { get; set; }
        public string Mail { get; set; }
        public string Web { get; set; }
        public Nullable<System.DateTime> OprettelsesDato { get; set; }
        public Nullable<System.DateTime> AfgangsDato { get; set; }
        public string Noter { get; set; }
        public string FoedtDato { get; set; }
        public Nullable<int> BemaerkningsId { get; set; }
        public string OprettetAf { get; set; }
        public string AendretAf { get; set; }
        public Nullable<System.DateTime> AendretDato { get; set; }
    }
}
