//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityAdapter
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeksterBreve
    {
        public string ForhandlerNummer { get; set; }
        public Nullable<int> Serie { get; set; }
        public Nullable<int> Traekning { get; set; }
        public string CVR_LL { get; set; }
        public string ForhandlerNavn { get; set; }
        public string ForhandlerAdresse { get; set; }
        public string ForhandlerPostNummer { get; set; }
        public string ForhandlerBy { get; set; }
        public string CPR_CVR { get; set; }
        public Nullable<System.DateTime> PeriodeStart { get; set; }
        public Nullable<System.DateTime> PeriodeSlut { get; set; }
        public string SalgTrk1 { get; set; }
        public string SalgTrk2 { get; set; }
        public string SalgTrk3 { get; set; }
        public string SalgTrk4 { get; set; }
        public string SalgTrk5 { get; set; }
        public string SalgTrk6 { get; set; }
        public string SalgAntalHele1 { get; set; }
        public string SalgAntalHele2 { get; set; }
        public string SalgAntalHele3 { get; set; }
        public string SalgAntalHele4 { get; set; }
        public string SalgAntalHele5 { get; set; }
        public string SalgAntalHele6 { get; set; }
        public string SalgAntalHalve1 { get; set; }
        public string SalgAntalHalve2 { get; set; }
        public string SalgAntalHalve3 { get; set; }
        public string SalgAntalHalve4 { get; set; }
        public string SalgAntalHalve5 { get; set; }
        public string SalgAntalHalve6 { get; set; }
        public string SalgAntalPbsHele { get; set; }
        public string SalgAntalPbsHalve { get; set; }
        public Nullable<decimal> PrisHel1 { get; set; }
        public Nullable<decimal> PrisHel2 { get; set; }
        public Nullable<decimal> PrisHel3 { get; set; }
        public Nullable<decimal> PrisHel4 { get; set; }
        public Nullable<decimal> PrisHel5 { get; set; }
        public Nullable<decimal> PrisHel6 { get; set; }
        public Nullable<decimal> PrisHalv1 { get; set; }
        public Nullable<decimal> PrisHalv2 { get; set; }
        public Nullable<decimal> PrisHalv3 { get; set; }
        public Nullable<decimal> PrisHalv4 { get; set; }
        public Nullable<decimal> PrisHalv5 { get; set; }
        public Nullable<decimal> PrisHalv6 { get; set; }
        public Nullable<decimal> PrisHelPbs { get; set; }
        public Nullable<decimal> PrisHalvPbs { get; set; }
        public string SalgTrkPbs { get; set; }
        public Nullable<decimal> SalgPrisHel1 { get; set; }
        public Nullable<decimal> SalgPrisHel2 { get; set; }
        public Nullable<decimal> SalgPrisHel3 { get; set; }
        public Nullable<decimal> SalgPrisHel4 { get; set; }
        public Nullable<decimal> SalgPrisHel5 { get; set; }
        public Nullable<decimal> SalgPrisHel6 { get; set; }
        public Nullable<decimal> SalgPrisHalv1 { get; set; }
        public Nullable<decimal> SalgPrisHalv2 { get; set; }
        public Nullable<decimal> SalgPrisHalv3 { get; set; }
        public Nullable<decimal> SalgPrisHalv4 { get; set; }
        public Nullable<decimal> SalgPrisHalv5 { get; set; }
        public Nullable<decimal> SalgPrisHalv6 { get; set; }
        public Nullable<decimal> SalgPrisPbsHele { get; set; }
        public Nullable<decimal> SalgPrisPbsHalve { get; set; }
        public Nullable<decimal> SalgPrisIalt1 { get; set; }
        public decimal SalgPrisIalt2 { get; set; }
        public Nullable<decimal> SalgPrisIalt3 { get; set; }
        public Nullable<decimal> SalgPrisIalt4 { get; set; }
        public Nullable<decimal> SalgPrisIalt5 { get; set; }
        public Nullable<decimal> SalgPrisIalt6 { get; set; }
        public Nullable<decimal> SalgPrisIalt { get; set; }
        public Nullable<decimal> SalgPrisIaltPbs { get; set; }
        public Nullable<decimal> ProvisionProcent { get; set; }
        public Nullable<decimal> ProvisionPbsProcent { get; set; }
        public Nullable<decimal> ProvisionSalg { get; set; }
        public Nullable<decimal> ProvisionPbs { get; set; }
        public Nullable<decimal> ProvisionTilMoms { get; set; }
        public Nullable<decimal> MomsProcent { get; set; }
        public Nullable<decimal> MomsBeloeb { get; set; }
        public Nullable<decimal> ProvisionInclMoms { get; set; }
        public Nullable<decimal> UdbetalteGevinster { get; set; }
        public Nullable<decimal> TidligereSaldo { get; set; }
        public Nullable<decimal> Posteringer { get; set; }
        public Nullable<decimal> BeloebIalt { get; set; }
        public string Postering1 { get; set; }
        public string Postering2 { get; set; }
        public string Postering3 { get; set; }
        public string Postering4 { get; set; }
        public string Postering5 { get; set; }
        public Nullable<decimal> ProvisionAarTilDato { get; set; }
    }
}
